Add venv to steps on self-hosted runners and env checks for installation. Cleaning or resetting of the self-hosted runners were added as well.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,6 +35,10 @@ jobs:
       with:
         python-version: ${{ matrix.python }}
 
+    - name: Create Python venv
+      run: |
+        python -m venv venv
+
     - name: Set CUDA version for the runner
       run: |
         CUDA_HOME="/usr/local/cuda-${{ matrix.cuda_version }}"
@@ -50,23 +54,34 @@ jobs:
 
     - name: Upgrade pip
       run: |
+        source venv/bin/activate
         python -m pip install -U pip>=22.3
 
     - name: Install the cupy wheel matching the CUDA version of the host
       run: |
+        source venv/bin/activate
         python tests/install_cupy.py
 
     - name: Install pybind11_cuda_array_interface for testing
       run: |
-        python -m pip install .[test]
+        source venv/bin/activate
+        BUILD_GTESTS=ON BUILD_PYTESTS=ON python -m pip install .[test]
 
     - name: Run Pytest
       run: |
+        source venv/bin/activate
         python -m pytest
 
     - name: Run GoogleTest
       run: |
+        source venv/bin/activate
         tests/gtest/run_gtest_cai
+
+    - name: Clean the self-hosted runner
+      if: always()
+      run: |
+        rm -rf venv
+        find $GITHUB_WORKSPACE/. ! -name . -prune -exec rm -rf {} +
 
 
 
@@ -108,6 +123,12 @@ jobs:
       with:
         name: pycai_source_build
         path: dist/*
+
+    - name: Store the install CuPy script
+      uses: actions/upload-artifact@v3
+      with:
+        name: install_cupy
+        path: tests/install_cupy.py
 
 
 
@@ -152,7 +173,7 @@ jobs:
         with:
           python-version: ${{ matrix.python }}
 
-      - name: Fetch packaged source build
+      - name: Fetch version from packaged source build
         uses: actions/download-artifact@v3
         with:
           name: pycai_version
@@ -176,18 +197,35 @@ jobs:
 
           echo "${CUDA_HOME}/bin" >> $GITHUB_PATH
 
+      - name: Create Python venv
+        run: |
+          python -m venv venv
+
       - name: Upgrade pip
         run: |
+          source venv/bin/activate
           python -m pip install -U pip>=22.3
+
+      - name: Fetch install_cupy.py script
+        uses: actions/download-artifact@v3
+        with:
+          name: install_cupy
 
       - name: Install the cupy wheel matching the CUDA version of the host
         run: |
-          python tests/install_cupy.py
+          source venv/bin/activate
+          python install_cupy.py
 
-    #   - name: Install pybind11_cuda_array_interface for testing
-    #     run: |
-    #       python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pybind11-cuda-array-interface[test]==${{ steps.get_version.outputs.VERSION }}
-    #     shell: bash
+      - name: Check that library is not present before installation
+        run: |
+          output=$(find / -name pybind11_cuda_array_interface.hpp 2>/dev/null || true)
+          if [ -n "$output" ]; then
+              echo "$output"
+              echo "Error: 'find' found 'pybind11_cuda_array_interface.hpp'"
+              exit 1
+          fi
+        shell: bash
+
         # Retries are needed since the upload to Test PyPI might not have been indexed yet after
         # the upload in the previous step.
       - name: Install pybind11_cuda_array_interface for testing
@@ -198,24 +236,23 @@ jobs:
           retry_wait_seconds: 60
           retry_on: error
           shell: bash
-          command: python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pybind11-cuda-array-interface[test]==${{ steps.get_version.outputs.VERSION }}
+          command: source venv/bin/activate && python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pybind11-cuda-array-interface==${{ steps.get_version.outputs.VERSION }}
 
-          
-
-
-
-
-
-
-
-
-      - name: Run Pytest
+      - name: Check that pycai headers are installed after the pip install command
         run: |
-          python -m pytest
-    
-      - name: Run GoogleTest
+          output=$(find / -name pybind11_cuda_array_interface.hpp 2>/dev/null || true)
+          if [ -z "$output" ]; then
+              echo "Error: 'find' did not find 'pybind11_cuda_array_interface.hpp'"
+              exit 1
+          fi
+        shell: bash
+
+      - name: Clean the self-hosted runner
+        if: always()
         run: |
-          tests/gtest/run_gtest_cai
+          rm -rf venv
+          find $GITHUB_WORKSPACE/. ! -name . -prune -exec rm -rf {} +
+        shell: bash
 
 
 
